title: Alvaro Esteban Github Pages
markdown: kramdown

# for atom feed
author: 
  name: alvaroesteban
  email: alvaroestebangonzalo@hotmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

paginate: 2
paginate_path: /blog/page:num/

google_analytics: G-49ZYZDQ7WN